### ISSUE TITLE
Removing personal roboports >MK2 from armor turns them into MK2 roboports

### ISSUE THREAD

**Issue by jlidtke** [McGuten/Factorio5DimMods#36]
Adding the line:

        equipment.take_result = "5d-personal-roboport-equipment-" .. inputs.number

to 5dim_core/lib/equipment/generation-personal-roboport-equipment.lua line 22 will fix the problem.

```
19    --Item
20    if inputs.new then
21        item.name = "5d-personal-roboport-equipment-" .. inputs.number
22        equipment.take_result = "5d-personal-roboport-equipment-" .. inputs.number
23    end
```

**Comment by NIronwolf** [comment]
Thanks for this.  It's been an issue for us.  :)

**Comment by torretto89** [comment]
I know this is old but I haven't found the answer anywhere else. I make this change but then the mod doesn't show up in my mod list anymore. Any help would be appreciated.

**Comment by NIronwolf** [comment]
> I know this is old but I haven't found the answer anywhere else. I make this change but then the mod doesn't show up in my mod list anymore. Any help would be appreciated.

Depends on how you make the edit.  If you unzip the mod to a folder of the same name and edit just the one file, you should be ok.  You can't just say take the one file out.  The "mod" needs to live as a .zip or a directory.

If it's a server, you may also want to change the version info by changing the directory/file name and updating info.json.  You'll then need to send that as a zip to anyone that plays because it won't be found on the mod portal.

**Comment by jrdiver** [comment]
Bumping this issue.... still a thing.  Would be nice to get this patched in officially someday
